### ISSUE TITLE
First_error

### ISSUE THREAD

**Issue by weizhiliang0520** [Saafke/FSRCNN_Tensorflow#4]
Traceback (most recent call last):
  File "/content/FSRCNN_Tensorflow/main.py", line 2, in <module>
    import fsrcnn
  File "/content/FSRCNN_Tensorflow/fsrcnn.py", line 8
    def model(x, y, lr_size, scale, batch, lr, (d, s, m)):
                                               ^
SyntaxError: invalid syntax

when beginning, it's wrong.

**Comment by mrgreen3325** [comment]
Hello wei,
Do u solve it?
I have another problem when training the model.
When I set batch = 8 and have 800 images for training, it only train 50 iterations in a epoch.
I think 800/8 = 100, it should be 100, right?
Do you have this problem?
Thanks.

**Comment by weizhiliang0520** [comment]
> Hello wei, Do u solve it? I have another problem when training the model. When I set batch = 8 and have 800 images for training, it only trains 50 iterations in a epoch. I think 800/8 = 100, it should be 100, right? Do you have this problem? Thanks.

yeah, you are right!

**Comment by weizhiliang0520** [comment]
> Hello wei, Do u solve it? I have another problem when training the model. When I set batch = 8 and have 800 images for training, it only train 50 iterations in a epoch. I think 800/8 = 100, it should be 100, right? Do you have this problem? Thanks.

i have not this problem since i meet the problem at first running the code!

**Comment by weizhiliang0520** [comment]
> > Hello wei, Do u solve it? I have another problem when training the model. When I set batch = 8 and have 800 images for training, it only trains 50 iterations in a epoch. I think 800/8 = 100, it should be 100, right? Do you have this problem? Thanks.
> 
> yeah, you are right!



> Hello wei, Do u solve it? I have another problem when training the model. When I set batch = 8 and have 800 images for training, it only train 50 iterations in a epoch. I think 800/8 = 100, it should be 100, right? Do you have this problem? Thanks.
